import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  hi: {
    appTitle: 'EcoBridge (इकोब्रिज)',
    greeting: 'नमस्ते, राजू',
    greetingRecycler: 'नमस्ते, इकोब्रिज रिसाइकलिंग',
    switchRoleCollector: 'कबाड़ीवाला व्यू',
    switchRoleRecycler: 'रिसाइक्लर व्यू',
    recyclerDashboardTitle: 'रिसाइक्लर डैशबोर्ड',
    tabHome: 'गृह',
    tabSell: 'बेचें',
    tabHistory: 'इतिहास',
    tabCommunity: 'समुदाय',
    camScan: 'कैमरा स्कैन',
    sellLot: 'लॉट बेचें',
    callBot: 'कॉल बॉट',
    history: 'इतिहास',
    todaysRates: 'आज का भाव',
    activeTx: 'सक्रिय लेन-देन',
    loyaltyPoints: 'लॉयल्टी पॉइंट्स',
    convertToUpi: 'UPI में बदलें',
    hardToSellTitle: 'मुश्किल स्क्रैप',
    hardToSellDesc: 'ई-वेस्ट, कठोर प्लास्टिक और मिश्रित स्क्रैप का विशेष भाव',
    batteryTitle: 'बैटरी रिकवरी',
    batteryDesc: 'गाड़ी और इन्वर्टर बैटरी का सुरक्षित और उच्चतम भाव',
    nearbyRecyclers: 'पास के रिसाइक्लर',
    safetyTips: 'सुरक्षा सुझाव',
    communityFeed: 'समुदाय',
    viewAll: 'सब देखें →',
    verifiedShield: 'अधिकृत',
    unverifiedShield: 'जांच लंबित',
    callNow: 'कॉल करें',
    status_online: 'ऑनलाइन',
    status_offline: 'ऑफ़लाइन (कैश्ड)',
    status_syncing: 'सिंक हो रहा है',
    syncPending: 'सिंक लंबित',
    cash: 'नकद',
    upi: 'UPI',
    anomalyNotice: 'यह भाव सामान्य से अलग है',
    myAccount: 'मेरा खाता',
    totalEarnings: 'कुल कमाई',
    totalLots: 'कुल बेचे गए लॉट',
    loyaltyBalance: 'लॉयल्टी अंक',
    completedTx: 'पूर्ण लेन-देन',
    pendingTx: 'बकाया लेन-देन',
    locationArea: 'कार्य क्षेत्र',
    editProfile: 'प्रोफाइल बदलें',
    saveProfile: 'सुरक्षित करें',
    sendOtp: 'भेजें',
    enterOtp: '4-अंकों का OTP दर्ज करें',
    resendOtp: 'OTP पुनः भेजें',
    selectLanguageTitle: 'भाषा चुनें',
    selectLanguageDesc: 'अपनी भाषा का चयन करें',
    tab_view: 'देखें',
    tab_edit: 'बदलें',
    end_call: 'कॉल समाप्त करें',
    understand_safety: 'सुरक्षा नियम स्वीकार किया',
    listening_required: 'दिशा-निर्देश देखें',
    gross_weight: 'कुल वजन',
    estimated_value: 'अनुमानित मूल्य',
    confirm_handover: 'हैंडओवर की पुष्टि करें',
    offlineStatus: 'ऑफ़लाइन मोड (कैश्ड डेटा)',
    pickupAvailable: 'पिकअप उपलब्ध',
    convertConfirmTitle: 'लॉयल्टी पॉइंट्स बदलें',
    convertConfirmDesc: 'क्या आप 1250 पॉइंट्स को ₹125 में बदलकर अपने जुड़े हुए UPI ID (ending ...1234) पर भेजना चाहते हैं?',
    convertSuccessToast: 'UPI ट्रांसफर सफल!',
    convertPointsReceipt: 'पॉइंट्स ट्रांसफर रसीद',
    resendTimerText: 'सेकंड बाद OTP पुनः भेजें',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    mobileNumberLabel: 'मोबाइल नंबर',
    termsPrivacyNotice: 'जारी रखकर आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं',
    eWasteImpactTitle: 'ई-कचरा प्रभाव एवं रिसायकलिंग',
    eWasteImpactDesc: 'सर्किट बोर्ड, लैंप और इलेक्ट्रॉनिक स्क्रैप का सुरक्षित निपटान',
    eWasteDiverted: '42.5 किग्रा',
    eWasteLabel: 'डाइवर्ट किया गया ई-वेस्ट',
    co2Saved: '128 किग्रा',
    co2Label: 'CO₂ बचत',
    scheduleEWastePickup: 'ई-वेस्ट पिकअप बुक करें',
    back: 'वापस',
    recyclerMatchingTitle: 'रिसाइक्लर मैचिंग',
    bestOffers: 'सर्वश्रेष्ठ ऑफर',
    selectOffer: 'यह ऑफर चुनें',
    offersReceived: 'ऑफर प्राप्त हुए',
    forWeight: 'के लिए',
    posted: 'पोस्ट हुआ',
    offer: 'ऑफर प्राप्त',
    accepted: 'स्वीकृत',
    handover: 'हैंडओवर',
    paid: 'भुगतान सफल',
    cameraScanTitle: 'फोटो स्कैन',
    cameraScanSub: 'स्क्रैप की फोटो लें या नीचे दी गई श्रेणी चुनें',
    scanningAi: 'AI विश्लेषण हो रहा है...',
    aiConfidence: 'AI पहचान',
    selectCategoryGrid: 'फोटो ग्रिड से श्रेणी चुनें',
    enterWeightBtn: 'वजन दर्ज करें',
    viewRecyclerOffers: 'रिसाइक्लर ऑफर देखें',
    scheduleEwastePickupBtn: 'ई-वेस्ट पिकअप शेड्यूल करें',
    rateAnomalyWarning: 'यह भाव सामान्य से अलग है',
    handoverChecklistTitle: 'सामग्री हैंडओवर',
    paymentMethodTitle: 'भुगतान का तरीका',
    cashPayment: 'नकद भुगतान',
    upiPayment: 'UPI डिजिटल भुगतान',
    pickupDateLabel: 'पिकअप तारीख',
    operatingAreaLabel: 'पिकअप स्थान',
    scheduleDetailsTitle: 'ई-वेस्ट पिकअप विवरण',
    faqTitle: 'ई-वेस्ट एवं सुरक्षा दिशानिर्देश',
    faqQ1: 'ई-वेस्ट (E-Waste) में क्या-क्या आता है?',
    faqA1: 'सर्किट बोर्ड (PCB), पुराने मोबाइल, लैपटॉप, टीवी, यूपीएस बैटरी, पावर केबल, और घरेलू इलेक्ट्रॉनिक उपकरण।',
    faqQ2: 'बैटरी निपटाते समय क्या सावधानियां रखें?',
    faqA2: 'बैटरी को कभी उल्टा न करें। रिसाव से बचने के लिए दस्ताने पहनें और केवल अधिकृत रिसाइक्लर को ही सौंपें।',
    faqQ3: 'ई-वेस्ट का सही भाव कैसे तय होता है?',
    faqA3: 'ई-वेस्ट का भाव उसमें मौजूद कीमती धातुओं (जैसे तांबा, चांदी) और सर्किट बोर्ड की श्रेणी के आधार पर तय होता है।',
    faqQ4: 'क्या डोरस्टेप पिकअप के लिए अतिरिक्त शुल्क लगता है?',
    faqA4: 'नहीं! हमारे अधिकृत पार्टनर पिकअप का कोई अतिरिक्त चार्ज नहीं लेते।',
    filterAll: 'सभी',
    filterAuthorized: 'अधिकृत',
    filterPickup: 'पिकअप उपलब्ध',
    voiceBotTitle: 'AI कॉल बॉट',
    voiceBotSub: 'बोलिए या नीचे दिए गए सुझाव पर टैप करें',
    voiceCmd1: 'तांबे का भाव बताओ',
    voiceCmd1Reply: 'तांबा आज 680 रुपये प्रति किलो बिक रहा है।',
    voiceCmd2: 'इन्वर्टर बैटरी कहाँ बेचूँ?',
    voiceCmd2Reply: 'इन्वर्टर बैटरी के लिए ग्रीन इंडिया रिसाइक्लर पर 95 रुपये किलो रेट मिल रहा है।',
    voiceCmd3: 'नया लॉट कैसे पोस्ट करें?',
    voiceCmd3Reply: 'कैमरा बटन दबाएं, फोटो खींचें, वजन दर्ज करें और तुरंत रेट पाएं।',
    liveYardRates: 'लाइव यार्ड रेट्स',
    sparklineView: 'चिप्स',
    trendGraphView: 'ट्रेंड ग्राफ',
    heroFastPickup: '⚡ तेज डोरस्टेप पिकअप',
    heroBannerTitle: 'घर बैठे कबाड़ी बेचें • उच्चतम भाव',
    heroBannerSub: 'डिजिटल वजन • तुरंत भुगतान',
    voiceBotPrompt: 'बोलिए, तांबा, लोहा या प्लास्टिक का क्या भाव चाहिए?',
    batteryCardHeadline: 'ई-कचरा व पुरानी बैटरी संभालें (₹95/किग्रा)',
    appSettingsTitle: 'मेरा खाता एवं सेटिंग्स',
    appLanguageLabel: 'ऐप की भाषा',
    activeModeLabel: 'सक्रिय मोड',
    faqSettingsButton: '❓ ई-वेस्ट गाइड व सुरक्षा प्रश्नोत्तर',
    langNameHi: 'हिंदी',
    langNameMr: 'मराठी',
    langNameEn: 'English',
    noVoiceNotesTitle: 'अभी कोई वॉइस नोट नहीं है',
    noVoiceNotesSub: 'अपने क्षेत्र में स्क्रैप भाव या सुरक्षा सुझाव शेयर करने वाले पहले व्यक्ति बनें!',
    createVoicePost: '+ वॉइस पोस्ट बनाएं',
    voiceComposerTitle: 'वॉइस नोट कम्पोज़र',
    recordingStatus: 'रिकॉर्डिंग...',
    tapMicPrompt: 'माइक पर टैप करें',
    postButton: 'पोस्ट करें',
    justNow: 'अभी-अभी',
    defaultAuthorName: 'राजू कबाड़ीवाला',
    defaultPostLocation: 'ओखला Phase 2',
    samplePostContent: 'आज ओखला यार्ड में तांबे का बहुत अच्छा भाव मिला!',
    allRecyclers: 'सभी रिसाइक्लर',
    onlyAuthorized: 'केवल अधिकृत',
    callingRecycler: 'रिसाइक्लर को कॉल किया जा रहा है',
    unverifiedTrader: 'अपुष्ट व्यापारी',
    authorizedRecycler: 'अधिकृत रिसाइक्लर',
    defaultProfileName: 'राजू कबाड़ीवाला',
    defaultOperatingArea: 'ओखला Phase 2, नई दिल्ली',
    otpSentVoice: 'OTP आपके मोबाइल नंबर पर भेज दिया गया है',
    loginSuccessVoice: 'लॉगिन सफल हुआ',
    appSubtitle: 'From Informal Collection to Formal Recycling',
    loginConfirmBtn: 'पुष्टि करें (लॉगिन)',
    verified: 'प्रमाणित'
  },
  mr: {
    appTitle: 'EcoBridge (इकोब्रिज)',
    greeting: 'नमस्कार, राजू',
    greetingRecycler: 'नमस्कार, इकोब्रिज रिसायकल',
    switchRoleCollector: 'कबाडीवाला व्ह्यू',
    switchRoleRecycler: 'रिसायकलर व्ह्यू',
    recyclerDashboardTitle: 'रिसायकलर डॅशबोर्ड',
    tabHome: 'मुख्य',
    tabSell: 'विक्री',
    tabHistory: 'इतिहास',
    tabCommunity: 'समुदाय',
    camScan: 'कॅमेरा स्कॅन',
    sellLot: 'माल विका',
    callBot: 'कॉल बॉट',
    history: 'इतिहास',
    todaysRates: 'आजचा भाव',
    activeTx: 'सक्रिय व्यवहार',
    loyaltyPoints: 'लॉयल्टी पॉइंट्स',
    convertToUpi: 'UPI मध्ये बदला',
    hardToSellTitle: 'कठीण स्क्रॅप',
    hardToSellDesc: 'विशेष ई-कचरा व प्लास्टिकसाठी उत्तम भाव',
    batteryTitle: 'बॅटरी रिकव्हरी',
    batteryDesc: 'गाडी व इन्व्हर्टर बॅटरीसाठी सुरक्षित विल्हेवाट',
    nearbyRecyclers: 'जवळील रिसायकलर',
    safetyTips: 'सुरक्षा सल्ला',
    communityFeed: 'समुदाय',
    viewAll: 'सर्व पहा →',
    verifiedShield: 'प्रमाणित',
    unverifiedShield: 'तपासणी बाकी',
    callNow: 'कॉल करा',
    status_online: 'ऑनलाइन',
    status_offline: 'ऑफलाइन (कॅश)',
    status_syncing: 'सिंक होत आहे',
    syncPending: 'सिंक बाकी',
    cash: 'रोख',
    upi: 'UPI',
    anomalyNotice: 'हा दर नेहमीपेक्षा वेगळा आहे',
    myAccount: 'माझे खाते',
    totalEarnings: 'एकूण कमाई',
    totalLots: 'एकूण विकलेले लॉट',
    loyaltyBalance: 'लॉयल्टी गुण',
    completedTx: 'पूर्ण व्यवहार',
    pendingTx: 'बाकी व्यवहार',
    locationArea: 'कार्य क्षेत्र',
    editProfile: 'प्रोफाइल बदला',
    saveProfile: 'जतन करा',
    sendOtp: 'पाठवा',
    enterOtp: '4-अंकी OTP टाका',
    resendOtp: 'पुन्हा पाठवा',
    selectLanguageTitle: 'भाषा निवडा',
    selectLanguageDesc: 'तुमची भाषा निवडा',
    tab_view: 'पहा',
    tab_edit: 'बदला',
    end_call: 'कॉल समाप्त करा',
    understand_safety: 'सुरक्षा नियम मान्य',
    listening_required: 'मार्गदर्शक सूचना पहा',
    gross_weight: 'एकूण वजन',
    estimated_value: 'अंदाजित मूल्य',
    confirm_handover: 'हँडओव्हरची पुष्टी करा',
    offlineStatus: 'ऑफलाइन मोड (कॅश डेटा)',
    pickupAvailable: 'पिकअप उपलब्ध',
    convertConfirmTitle: 'लॉयल्टी पॉइंट्स बदला',
    convertConfirmDesc: 'तुम्हाला १२५० पॉइंट्स ₹१२५ मध्ये बदलून तुमच्या UPI ID (...1234) वर पाठवायचे आहेत का?',
    convertSuccessToast: 'UPI ट्रान्सफर यशस्वी!',
    convertPointsReceipt: 'पॉइंट्स ट्रान्सफर पावती',
    resendTimerText: 'सेकंदात पुन्हा OTP पाठवा',
    cancel: 'रद्द करा',
    confirm: 'खात्री करा',
    mobileNumberLabel: 'मोबाइल नंबर',
    termsPrivacyNotice: 'पुढे चालू ठेवून तुम्ही आमच्या अटी व गोपनीयता धोरणाशी सहमत आहात',
    eWasteImpactTitle: 'ई-कचरा प्रभाव व रिसायकलिंग',
    eWasteImpactDesc: 'सर्किट बोर्ड, लॅम्प्स आणि इलेक्ट्रॉनिक कचऱ्याचे सुरक्षित व्यवस्थापन',
    eWasteDiverted: '42.5 किलो',
    eWasteLabel: 'डायव्हर्ट केलेला ई-कचरा',
    co2Saved: '128 किलो',
    co2Label: 'CO₂ बचत',
    scheduleEWastePickup: 'ई-कचरा पिकअप बुक करा',
    back: 'मागे',
    recyclerMatchingTitle: 'रिसायकलर मॅचिंग',
    bestOffers: 'उत्तम ऑफर्स',
    selectOffer: 'ही ऑफर निवडा',
    offersReceived: 'ऑफर्स मिळाले',
    forWeight: 'साठी',
    posted: 'पोस्ट झाले',
    offer: 'ऑफर मिळाली',
    accepted: 'मान्य',
    handover: 'हँडओव्हर',
    paid: 'पैसे भरले',
    cameraScanTitle: 'कॅमेरा स्कॅन',
    cameraScanSub: 'स्क्रॅपचा फोटो घ्या किंवा खालील श्रेणी निवडा',
    scanningAi: 'AI विश्लेषण होत आहे...',
    aiConfidence: 'AI ओळख',
    selectCategoryGrid: 'फोटो ग्रिडवरून श्रेणी निवडा',
    enterWeightBtn: 'वजन टाका',
    viewRecyclerOffers: 'रिसायकलर ऑफर्स पहा',
    scheduleEwastePickupBtn: 'ई-कचरा पिकअप बुक करा',
    rateAnomalyWarning: 'हा दर सामान्यपेक्षा वेगळा आहे',
    handoverChecklistTitle: 'माल हँडओव्हर',
    paymentMethodTitle: 'पेमेंट पद्धत',
    cashPayment: 'रोख पेमेंट',
    upiPayment: 'UPI डिजिटल पेमेंट',
    pickupDateLabel: 'पिकअप तारीख',
    operatingAreaLabel: 'पिकअप ठिकाण',
    scheduleDetailsTitle: 'ई-कचरा पिकअप माहिती',
    faqTitle: 'ई-कचरा व सुरक्षा मार्गदर्शक',
    faqQ1: 'ई-कचऱ्यामध्ये काय येते?',
    faqA1: 'सर्किट बोर्ड, मोबाईल, लॅपटॉप, टीव्ही, बॅटरी, केबल्स आणि इलेक्ट्रॉनिक वस्तू.',
    faqQ2: 'बॅटरी विल्हेवाट लावताना काय काळजी घ्यावी?',
    faqA2: 'बॅटरी उलटी करू नका. हातमोजे वापरा व अधिकृत रिसायकलरकडे द्या.',
    faqQ3: 'ई-कचऱ्याचा दर कसा ठरतो?',
    faqA3: 'त्यातील मौल्यवान धातू आणि सर्किट बोर्डच्या श्रेणीनुसार दर ठरतो.',
    faqQ4: 'डोरस्टेप पिकअपसाठी अतिरिक्त शुल्क आहे का?',
    faqA4: 'नाही! पिकअप पूर्णपणे मोफत आहे.',
    filterAll: 'सर्व',
    filterAuthorized: 'प्रमाणित',
    filterPickup: 'पिकअप उपलब्ध',
    voiceBotTitle: 'AI कॉल बॉट',
    voiceBotSub: 'बोला किंवा खालील बटणावर क्लिक करा',
    voiceCmd1: 'तांब्याचा भाव सांगा',
    voiceCmd1Reply: 'तांबे आज ६८० रुपये किलो आहे.',
    voiceCmd2: 'इन्व्हर्टर बॅटरी कुठे विकू?',
    voiceCmd2Reply: 'इन्व्हर्टर बॅटरीसाठी ९५ रुपये किलो दर आहे.',
    voiceCmd3: 'नवीन लॉट कसा पोस्ट करावा?',
    voiceCmd3Reply: 'कॅमेरा बटणावर क्लिक करा, फोटो घ्या व वजन टाका.',
    liveYardRates: 'लाइव्ह दर',
    sparklineView: 'चिप्स',
    trendGraphView: 'ट्रेंड आलेख',
    heroFastPickup: '⚡ वेगवान डोअरस्टेप पिकअप',
    heroBannerTitle: 'घरी बसून कबाडी विका • सर्वोत्कृष्ट भाव',
    heroBannerSub: 'डिजिटल वजन • त्वरित पेमेंट',
    voiceBotPrompt: 'बोला, तांबे, लोखंड किंवा प्लास्टिकचा काय भाव हवा आहे?',
    batteryCardHeadline: 'ई-कचरा व जुनी बॅटरी सांभाळा (₹95/किग्रा)',
    appSettingsTitle: 'माझे खाते व सेटिंग्ज',
    appLanguageLabel: 'ॲपची भाषा',
    activeModeLabel: 'सक्रिय मोड',
    faqSettingsButton: '❓ ई-कचरा मार्गदर्शक व सुरक्षा FAQ',
    langNameHi: 'हिंदी',
    langNameMr: 'मराठी',
    langNameEn: 'English',
    noVoiceNotesTitle: 'अद्याप कोणतेही व्हॉइस नोट नाहीत',
    noVoiceNotesSub: 'तुमच्या क्षेत्रातील स्क्रॅप भाव किंवा सुरक्षा सल्ला शेअर करणारे पहिले व्हा!',
    createVoicePost: '+ व्हॉइस पोस्ट तयार करा',
    voiceComposerTitle: 'व्हॉइस नोट कम्पोझर',
    recordingStatus: 'रेकॉर्डिंग...',
    tapMicPrompt: 'माइकवर टॅप करा',
    postButton: 'पोस्ट करा',
    justNow: 'आत्ताच',
    defaultAuthorName: 'राजू कबाडीवाला',
    defaultPostLocation: 'ओखला Phase 2',
    samplePostContent: 'आज ओखला यार्डमध्ये तांब्याचा उत्तम भाव मिळाला!',
    allRecyclers: 'सर्व रिसायकलर',
    onlyAuthorized: 'फक्त प्रमाणित',
    callingRecycler: 'रिसायकलरला कॉल केला जात आहे',
    unverifiedTrader: 'अप्रमाणित व्यापारी',
    authorizedRecycler: 'प्रमाणित रिसायकलर',
    defaultProfileName: 'राजू कबाडीवाला',
    defaultOperatingArea: 'ओखला Phase 2, नवी दिल्ली',
    otpSentVoice: 'OTP तुमच्या मोबाईल नंबरवर पाठवला आहे',
    loginSuccessVoice: 'लॉगिन यशस्वी झाले',
    appSubtitle: 'From Informal Collection to Formal Recycling',
    loginConfirmBtn: 'खात्री करा (लॉगिन)',
    verified: 'प्रमाणित'
  },
  en: {
    appTitle: 'EcoBridge',
    greeting: 'Hello, Raju',
    greetingRecycler: 'Hello, Green Recycle',
    switchRoleCollector: 'Collector View',
    switchRoleRecycler: 'Recycler View',
    recyclerDashboardTitle: 'Recycler Dashboard',
    tabHome: 'Home',
    tabSell: 'Sell',
    tabHistory: 'History',
    tabCommunity: 'Community',
    camScan: 'Camera Scan',
    sellLot: 'Sell Lot',
    callBot: 'Voice Bot',
    history: 'History',
    todaysRates: "Today's Rates",
    activeTx: 'Active Transaction',
    loyaltyPoints: 'Loyalty Points',
    convertToUpi: 'Convert to UPI',
    hardToSellTitle: 'Hard-to-Sell Materials',
    hardToSellDesc: 'Unlock hidden value for e-waste & hard plastics',
    batteryTitle: 'Battery Recovery',
    batteryDesc: 'Vehicle & inverter lead-acid battery safe disposal',
    nearbyRecyclers: 'Nearby Recyclers',
    safetyTips: 'Safety Tips',
    communityFeed: 'Community Feed',
    viewAll: 'View All →',
    verifiedShield: 'Authorized',
    unverifiedShield: 'Unverified',
    callNow: 'Call Now',
    status_online: 'Online',
    status_offline: 'Offline (Cached)',
    status_syncing: 'Syncing',
    syncPending: 'Sync Pending',
    cash: 'Cash',
    upi: 'UPI',
    anomalyNotice: 'This rate is unusual compared to historical trends',
    myAccount: 'My Account',
    totalEarnings: 'Total Earnings',
    totalLots: 'Total Lots Sold',
    loyaltyBalance: 'Loyalty Balance',
    completedTx: 'Completed Transactions',
    pendingTx: 'Pending Transactions',
    locationArea: 'Operating Area',
    editProfile: 'Edit Profile',
    saveProfile: 'Save Profile',
    sendOtp: 'Send OTP',
    enterOtp: 'Enter 4-digit OTP',
    resendOtp: 'Resend OTP',
    selectLanguageTitle: 'Select Language',
    selectLanguageDesc: 'Choose your preferred language',
    tab_view: 'View',
    tab_edit: 'Edit',
    end_call: 'End Call',
    understand_safety: 'Accept Safety Rules',
    listening_required: 'View Guidelines',
    gross_weight: 'Gross Weight',
    estimated_value: 'Estimated Valuation',
    confirm_handover: 'Confirm Handover',
    offlineStatus: 'Offline Mode (Cached Data)',
    pickupAvailable: 'Pickup Available',
    convertConfirmTitle: 'Convert Loyalty Points',
    convertConfirmDesc: 'Convert 1250 points to ₹125 and transfer to your linked UPI ID ending in ...1234?',
    convertSuccessToast: 'UPI Transfer Successful!',
    convertPointsReceipt: 'Points Transfer Receipt',
    resendTimerText: 'Resend OTP in seconds',
    cancel: 'Cancel',
    confirm: 'Confirm',
    mobileNumberLabel: 'Mobile Number',
    termsPrivacyNotice: 'By continuing you agree to Terms & Privacy Policy',
    eWasteImpactTitle: 'E-Waste Environmental Impact',
    eWasteImpactDesc: 'Safely divert circuit boards, batteries, & electronics from landfills',
    eWasteDiverted: '42.5 kg',
    eWasteLabel: 'Diverted E-Waste',
    co2Saved: '128 kg',
    co2Label: 'CO₂ Prevented',
    scheduleEWastePickup: 'Schedule E-Waste Pickup',
    back: 'Back',
    recyclerMatchingTitle: 'Recycler Matching',
    bestOffers: 'Best Recycler Offers',
    selectOffer: 'Select Offer',
    offersReceived: 'offers received',
    forWeight: 'for',
    posted: 'Posted',
    offer: 'Offer Received',
    accepted: 'Accepted',
    handover: 'Handover',
    paid: 'Payment Complete',
    cameraScanTitle: 'Photo Scan',
    cameraScanSub: 'Take scrap photo or select category from grid',
    scanningAi: 'Analyzing AI photo...',
    aiConfidence: 'AI Recognized',
    selectCategoryGrid: 'Select Category from Photo Grid',
    enterWeightBtn: 'Enter Weight',
    viewRecyclerOffers: 'View Recycler Offers',
    scheduleEwastePickupBtn: 'Schedule E-Waste Pickup',
    rateAnomalyWarning: 'Unusual Rate Anomaly',
    handoverChecklistTitle: 'Material Handover',
    paymentMethodTitle: 'Payment Method',
    cashPayment: 'Cash Payment',
    upiPayment: 'UPI Digital Payment',
    pickupDateLabel: 'Pickup Date',
    operatingAreaLabel: 'Pickup Location',
    scheduleDetailsTitle: 'E-Waste Pickup Details',
    faqTitle: 'E-Waste & Safety Guidelines',
    faqQ1: 'What qualifies as E-Waste?',
    faqA1: 'Circuit boards (PCB), old phones, laptops, TVs, batteries, power cables, and electronics.',
    faqQ2: 'What safety precautions to follow for batteries?',
    faqA2: 'Never invert batteries. Wear gloves for leaks and hand over to authorized recyclers only.',
    faqQ3: 'How is E-Waste valuation determined?',
    faqA3: 'Valuation is based on precious metals (copper, silver) and circuit board grading.',
    faqQ4: 'Is there any fee for doorstep pickup?',
    faqA4: 'No! Our authorized partners provide doorstep pickup free of extra charge.',
    filterAll: 'All',
    filterAuthorized: 'Authorized',
    filterPickup: 'Pickup Available',
    voiceBotTitle: 'AI Call Bot',
    voiceBotSub: 'Speak or tap a suggestion below',
    voiceCmd1: 'Get Copper Rates',
    voiceCmd1Reply: 'Copper is currently trading at ₹680 per kg.',
    voiceCmd2: 'Where to sell inverter battery?',
    voiceCmd2Reply: 'Green Recycle is buying inverter batteries at ₹95/kg.',
    voiceCmd3: 'How to post a new lot?',
    voiceCmd3Reply: 'Tap camera scan, take photo, enter weight and receive live quotes.',
    liveYardRates: 'Live Yard Rates',
    sparklineView: 'Chips',
    trendGraphView: 'Trend Graph',
    heroFastPickup: '⚡ Fast Doorstep Pickup',
    heroBannerTitle: 'Sell Scrap at Home • Best Rates',
    heroBannerSub: 'Digital Weight • Instant Payment',
    voiceBotPrompt: 'Speak, what rate do you need for copper, iron or plastic?',
    batteryCardHeadline: 'Recycle E-Waste & Batteries (₹95/kg)',
    appSettingsTitle: 'My Account & Settings',
    appLanguageLabel: 'App Language',
    activeModeLabel: 'Active Mode',
    faqSettingsButton: '❓ E-Waste Guide & Safety FAQ',
    langNameHi: 'हिंदी',
    langNameMr: 'मराठी',
    langNameEn: 'English',
    noVoiceNotesTitle: 'No Voice Notes Yet',
    noVoiceNotesSub: 'Be the first to share scrap market rates or safety tips in your area!',
    createVoicePost: '+ Create Voice Post',
    voiceComposerTitle: 'Voice Note Composer',
    recordingStatus: 'Recording...',
    tapMicPrompt: 'Tap on mic to start',
    postButton: 'Post',
    justNow: 'Just now',
    defaultAuthorName: 'Raju (Collector)',
    defaultPostLocation: 'Okhla Phase 2',
    samplePostContent: 'Got great rates for copper at Okhla yard today!',
    allRecyclers: 'All Recyclers',
    onlyAuthorized: 'Only Authorized',
    callingRecycler: 'Connecting call to recycler',
    unverifiedTrader: 'Unverified Trader',
    authorizedRecycler: 'Authorized Recycler',
    defaultProfileName: 'Raju (Collector)',
    defaultOperatingArea: 'Okhla Phase 2, New Delhi',
    otpSentVoice: 'OTP has been sent to your mobile number',
    loginSuccessVoice: 'Login successful',
    appSubtitle: 'From Informal Collection to Formal Recycling',
    loginConfirmBtn: 'Confirm (Login)',
    verified: 'Verified',
    receiptTitle: 'Official Booking Receipt',
    settlementReceiptTitle: 'Digital Settlement Receipt',
    bookingRef: 'Booking Reference',
    pickupSlot: 'Scheduled Slot',
    itemDetails: 'Itemized Material Valuation',
    unitRate: 'Rate per kg',
    totalAmount: 'Total Payable Amount',
    ecoImpactCert: 'Environmental Impact Certificate',
    co2Diverted: 'CO₂ Avoided & E-Waste Recovered',
    downloadReceipt: 'Download Receipt (PDF)',
    shareWhatsapp: 'Share via WhatsApp',
    authorizedSeal: 'Govt. Authorized Eco-Recycling Seal',
    viewReceipt: 'View Official Receipt',
    closeReceipt: 'Close Receipt',
    proxyCallTitle: 'Secure Call-Masking',
    privacyNoticeNote: 'Your number stays 100% private — calls are routed securely via virtual proxy line.',
    dialProxyButton: 'Dial Secure Line',
    proxyNumberLabel: 'Virtual Proxy Line',
    sessionExpiresIn: 'Virtual Line Valid For',
    callFailedMsg: 'Call Proxy Unreachable. Retrying secure connection...',
    connectingProxy: 'Connecting Encrypted Line...'
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('ecobridge_lang') || localStorage.getItem('kabadiwala_lang') || 'hi';
  });

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('ecobridge_lang', newLang);
  };

  const t = (key) => {
    const val = TRANSLATIONS[lang]?.[key] || TRANSLATIONS['hi']?.[key] || TRANSLATIONS['en']?.[key];
    if (val) return val;
    // Fallback: format camelCase/snake_case to human-readable string if key is missing
    return key
      .replace(/([A-Z])/g, ' $1')
      .replace(/_/g, ' ')
      .replace(/^./, str => str.toUpperCase())
      .trim();
  };

  // Section 2.3 Strict Single-Language Resolution Rule
  const getLangText = (obj) => {
    if (!obj) return '';
    if (typeof obj === 'string') return obj;
    return obj[lang] || obj['hi'] || obj['en'] || Object.values(obj)[0] || '';
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, t, getLangText }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
